 package com.masterpushers.pass_assist.utils

import android.util.Base64
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

object EncryptionUtils {
    private const val ALGORITHM = "AES"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val KEY_SIZE = 256
    private const val GCM_IV_LENGTH = 12
    private const val GCM_TAG_LENGTH = 128

    /**
     * Generates a secure AES key
     */
    fun generateKey(): SecretKey {
        val keyGenerator = KeyGenerator.getInstance(ALGORITHM)
        keyGenerator.init(KEY_SIZE)
        return keyGenerator.generateKey()
    }

    /**
     * Encrypts the given plaintext using the provided key
     * Handles both Android Keystore keys and regular keys
     */
    fun encrypt(plaintext: String, key: SecretKey): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        
        // Try to initialize with a manually generated IV first
        // If this fails, it's likely an Android Keystore key that doesn't allow manual IV
        return try {
            // For regular keys, manually generate IV
            val iv = ByteArray(GCM_IV_LENGTH)
            SecureRandom().nextBytes(iv)
            val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
            cipher.init(Cipher.ENCRYPT_MODE, key, spec)
            val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
            val encryptedData = ByteArray(iv.size + ciphertext.size)
            System.arraycopy(iv, 0, encryptedData, 0, iv.size)
            System.arraycopy(ciphertext, 0, encryptedData, iv.size, ciphertext.size)
            Base64.encodeToString(encryptedData, Base64.DEFAULT)
        } catch (e: java.security.InvalidAlgorithmParameterException) {
            // If providing IV fails, it's an Android Keystore key
            // Android Keystore keys don't allow manually providing IV - let cipher generate it
            cipher.init(Cipher.ENCRYPT_MODE, key)
            val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
            // Get the IV that was automatically generated by the cipher
            val iv = cipher.iv
            if (iv != null && iv.isNotEmpty()) {
                // Prepend IV to ciphertext
                val encryptedData = ByteArray(iv.size + ciphertext.size)
                System.arraycopy(iv, 0, encryptedData, 0, iv.size)
                System.arraycopy(ciphertext, 0, encryptedData, iv.size, ciphertext.size)
                Base64.encodeToString(encryptedData, Base64.DEFAULT)
            } else {
                // This shouldn't happen, but if IV is not available, throw an exception
                throw IllegalStateException("Failed to retrieve IV from cipher after encryption", e)
            }
        }
    }

    /**
     * Decrypts the given ciphertext using the provided key
     * Handles both Android Keystore keys and regular keys
     */
    fun decrypt(ciphertext: String, key: SecretKey): String {
        val decodedData = Base64.decode(ciphertext, Base64.DEFAULT)
        
        // Check if we have enough data for IV + ciphertext
        if (decodedData.size < GCM_IV_LENGTH) {
            throw IllegalArgumentException("Invalid ciphertext: too short")
        }
        
        // Extract IV from the beginning of the encrypted data
        val iv = ByteArray(GCM_IV_LENGTH)
        System.arraycopy(decodedData, 0, iv, 0, iv.size)
        val encryptedBytes = ByteArray(decodedData.size - iv.size)
        System.arraycopy(decodedData, iv.size, encryptedBytes, 0, encryptedBytes.size)
        
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        
        // Try to initialize with the extracted IV
        // This should work for both Keystore and regular keys during decryption
        cipher.init(Cipher.DECRYPT_MODE, key, spec)
        val decryptedBytes = cipher.doFinal(encryptedBytes)
        return String(decryptedBytes, Charsets.UTF_8)
    }

    /**
     * Converts a SecretKey to a Base64 encoded string
     */
    fun keyToString(key: SecretKey): String {
        return Base64.encodeToString(key.encoded, Base64.DEFAULT)
    }

    /**
     * Converts a Base64 encoded string to a SecretKey
     */
    fun stringToKey(encodedKey: String): SecretKey {
        val decodedKey = Base64.decode(encodedKey, Base64.DEFAULT)
        return SecretKeySpec(decodedKey, 0, decodedKey.size, ALGORITHM)
    }
}